import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { SessionContext, SessionProvider } from "next-auth/react";
import LogoutBtn from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "forum2",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  <SessionProvider>{children}</SessionProvider>;
  let session = await getServerSession(authOptions);
  console.log(session);

  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Xylon_forum2
          </Link>
          <Link href="/list">List🙉</Link>
          <Link href="/write">Write📝</Link>
          {session ? (
            <span>
              {session.user.name} <LogoutBtn />{" "}
            </span>
          ) : (
            <LoginBtn></LoginBtn>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
